### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Parker-Williams-Smoothstack**
Primarily just adding the boilerplate code, but also includes the rough outline for reading/getting from the Card and Loan tables. Also included psuedocode for generating the card numbers as well as explanations on the process, but as far as the code goes it is restricted to Reading.

### CODE REVIEW

**Comment by ghost** [comment]
Is the Card DE the information you are planning on showing the user when they view the cards they can sign up for?

**Comment by Parker-Williams-Smoothstack** [comment]
> Is the Card DE the information you are planning on showing the user when they view the cards they can sign up for?

Largely, yes, the Card DE will be the things I expect the user to see when looking at available cards or cards they have registered for. It's going to contain most of the information needed, but any high level details will likely be covered elsewhere. For example, the CardDE will give details like if it's a credit or debit card and possibly information like the interest rates, but big marketing descriptions and promotions like "Are you looking for a card that..." will be on the site instead. Depending on how things are set we can add or remove fields as needed.

**Comment by ghost** [comment]
I'm wondering if maybe you could split that up into two tables: a card_type table and a card table (names tbd). So the card_type would be read only info with the info like interest rate, type of card (debit/credit), cashback, etc, and that could be displayed on the front end, and then the other card table would be the one that has a foreign key for user and card_type and then would also have the balance.

**Comment by Parker-Williams-Smoothstack** [comment]
That would work pretty well. I'd keep the cash-back amount in the main card table though since it depends on the specific card (don't want all debit cards to share the same cash-back pool) but other than that it sounds like a good idea. I'll make that change and add the card_type table as well as move some of the fields around to it.

**Comment by Parker-Williams-Smoothstack** [comment]
Added those changes and pushed them so give those a look over whenever and see if that's more what you were thinking.

**Review by ghost — APPROVED** [review]
Looks good

**Pull request merged**
